-- H2 2.2.224;
;             
CREATE USER IF NOT EXISTS "ADMIN" SALT 'd472e0a2855779ea' HASH '2bfeb30f04c376fa8045435a86e26cbf6308738280dc08e6645c8db2640eac58' ADMIN;      
CREATE SEQUENCE "PUBLIC"."CLSRDCIMMAGINE_SEQ" START WITH 1 RESTART WITH 51 INCREMENT BY 50;   
CREATE SEQUENCE "PUBLIC"."CLSRDCNODO_SEQ" START WITH 1 INCREMENT BY 50;       
CREATE SEQUENCE "PUBLIC"."CLS_COMUNE_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50;      
CREATE SEQUENCE "PUBLIC"."CLS_IMMAGINE_SEQ" START WITH 1 INCREMENT BY 50;     
CREATE SEQUENCE "PUBLIC"."CLS_ITINERARIO_SEQ" START WITH 1 INCREMENT BY 50;   
CREATE SEQUENCE "PUBLIC"."CLS_NODO_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50;        
CREATE SEQUENCE "PUBLIC"."CLS_RDC_ITINERARIO_SEQ" START WITH 1 INCREMENT BY 50;               
CREATE SEQUENCE "PUBLIC"."CLS_RECENSIONE_SEQ" START WITH 1 RESTART WITH 51 INCREMENT BY 50;   
CREATE SEQUENCE "PUBLIC"."CLS_SEGNALAZIONE_SEQ" START WITH 1 INCREMENT BY 50; 
CREATE SEQUENCE "PUBLIC"."CLS_TURISTA_AUTENTICATO_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50;         
CREATE MEMORY TABLE "PUBLIC"."CLS_COMUNE"(
    "ABITANTI" INTEGER NOT NULL,
    "SUPERFICIE" FLOAT(53) NOT NULL,
    "CURATORI_ASSOCIATI_ID" BIGINT,
    "ID" BIGINT NOT NULL,
    "DESCRIZIONE" CHARACTER VARYING(255),
    "NOME" CHARACTER VARYING(255),
    "POSIZIONE" CHARACTER VARYING(255),
    "USERNAME_CREATORE" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."CLS_COMUNE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B9" PRIMARY KEY("ID");  
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.CLS_COMUNE;              
INSERT INTO "PUBLIC"."CLS_COMUNE" VALUES
(0, 321.0, NULL, 1, 'Una strada, un tabacchi e un autovelox', 'Canepona', '12.1 12.3', 'ADMIN'),
(0, 123.0, NULL, 2, 'Spavento', 'Spello', '14.4 18.9', 'ADMIN'),
(0, 213.0, NULL, 3, 'Capitale', 'Castelraimondo', '32.0 31.0', 'ADMIN');        
CREATE MEMORY TABLE "PUBLIC"."CLS_CONTEST_DI_CONTRIBUZIONE"(
    "IS_APERTO" BOOLEAN NOT NULL,
    "DURATA" TIMESTAMP(6),
    "LOCATION_ID" BIGINT,
    "ID" CHARACTER VARYING(255) NOT NULL,
    "USERNAME_CREATORE" CHARACTER VARYING(255)
);         
ALTER TABLE "PUBLIC"."CLS_CONTEST_DI_CONTRIBUZIONE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3A" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CLS_CONTEST_DI_CONTRIBUZIONE;            
CREATE MEMORY TABLE "PUBLIC"."CLS_IMMAGINE"(
    "ID" BIGINT NOT NULL,
    "ID_CON1" CHARACTER VARYING(255),
    "URL" CHARACTER VARYING(255),
    "USERNAME_CREATORE" CHARACTER VARYING(255)
);         
ALTER TABLE "PUBLIC"."CLS_IMMAGINE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CLS_IMMAGINE;            
CREATE MEMORY TABLE "PUBLIC"."CLS_ITINERARIO"(
    "ORDINATO" BOOLEAN NOT NULL,
    "ID" BIGINT NOT NULL,
    "NOME" CHARACTER VARYING(255),
    "USERNAME_CREATORE" CHARACTER VARYING(255)
);           
ALTER TABLE "PUBLIC"."CLS_ITINERARIO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_32" PRIMARY KEY("ID");              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CLS_ITINERARIO;          
CREATE MEMORY TABLE "PUBLIC"."CLS_ITINERARIO_TAPPE"(
    "CLS_ITINERARIO_ID" BIGINT NOT NULL,
    "TAPPE_ID" BIGINT NOT NULL
);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CLS_ITINERARIO_TAPPE;    
CREATE MEMORY TABLE "PUBLIC"."CLS_NODO"(
    "A_TEMPO" BOOLEAN NOT NULL,
    "E_TOLOGIA_NODO" TINYINT,
    "ID" BIGINT NOT NULL,
    "DATA_FINE" CHARACTER VARYING(255),
    "DATA_INIZIO" CHARACTER VARYING(255),
    "DESCRIZIONE" CHARACTER VARYING(255),
    "ID_COMUNE" CHARACTER VARYING(255),
    "NOME" CHARACTER VARYING(255),
    "POSIZIONE" CHARACTER VARYING(255),
    "USERNAME_CREATORE" CHARACTER VARYING(255)
);  
ALTER TABLE "PUBLIC"."CLS_NODO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_77" PRIMARY KEY("ID");    
-- 5 +/- SELECT COUNT(*) FROM PUBLIC.CLS_NODO;
INSERT INTO "PUBLIC"."CLS_NODO" VALUES
(TRUE, 1, 1, NULL, NULL, 'Ciao', 'Camerino', 'Centro Camerino', '12.0 23.0', NULL),
(TRUE, 1, 2, NULL, NULL, 'Ciao', 'Camerino', 'Porchettaro', '12.0 23.0', NULL),
(TRUE, 1, 3, NULL, NULL, 'Museo con reperti storici', 'Macerata', 'Museo Civico', '15.0 30.0', NULL),
(TRUE, 1, 4, NULL, NULL, 'Antico teatro romano', 'Fermo', 'Teatro Romano', '14.0 28.0', NULL),
(FALSE, 2, 5, NULL, NULL, 'Parco con flora e fauna locali', 'Ascoli Piceno', 'Parco Naturale', '13.0 25.0', NULL);       
CREATE MEMORY TABLE "PUBLIC"."CLSRDCIMMAGINE"(
    "CREATORE_ID" BIGINT,
    "ID_RICHIESTA" BIGINT NOT NULL,
    "NEW_DATA_ID" BIGINT,
    "OLD_DATA_ID" BIGINT,
    "RESPONSABILE_ID" BIGINT,
    "ID_CONTEST_ID" CHARACTER VARYING(255),
    "STATO" CHARACTER VARYING(255),
    "TIPO" CHARACTER VARYING(255)
);  
ALTER TABLE "PUBLIC"."CLSRDCIMMAGINE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_DCC" PRIMARY KEY("ID_RICHIESTA");   
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.CLSRDCIMMAGINE;          
INSERT INTO "PUBLIC"."CLSRDCIMMAGINE" VALUES
(6, 1, NULL, NULL, NULL, NULL, 'NUOVO', 'INSERISCI_IMMAGINE');  
CREATE MEMORY TABLE "PUBLIC"."CLS_RDC_ITINERARIO"(
    "CREATORE_ID" BIGINT,
    "ID_RICHIESTA" BIGINT NOT NULL,
    "NEW_DATA_ID" BIGINT,
    "OLD_DATA_ID" BIGINT,
    "RESPONSABILE_ID" BIGINT,
    "ID_CONTEST_ID" CHARACTER VARYING(255),
    "STATO" CHARACTER VARYING(255),
    "TIPO" CHARACTER VARYING(255)
);              
ALTER TABLE "PUBLIC"."CLS_RDC_ITINERARIO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5EA" PRIMARY KEY("ID_RICHIESTA");               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CLS_RDC_ITINERARIO;      
CREATE MEMORY TABLE "PUBLIC"."CLSRDCNODO"(
    "CREATORE_ID" BIGINT,
    "ID_RICHIESTA" BIGINT NOT NULL,
    "NEW_DATA_ID" BIGINT,
    "OLD_DATA_ID" BIGINT,
    "RESPONSABILE_ID" BIGINT,
    "ID_CONTEST_ID" CHARACTER VARYING(255),
    "STATO" CHARACTER VARYING(255),
    "TIPO" CHARACTER VARYING(255)
);      
ALTER TABLE "PUBLIC"."CLSRDCNODO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B286" PRIMARY KEY("ID_RICHIESTA");      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CLSRDCNODO;              
CREATE MEMORY TABLE "PUBLIC"."CLS_RECENSIONE"(
    "VALUTAZIONE" FLOAT(53) NOT NULL,
    "ID" BIGINT NOT NULL,
    "CONTENUTO" CHARACTER VARYING(255),
    "ID_CONTENUTO2" CHARACTER VARYING(255),
    "OGGETTO" CHARACTER VARYING(255),
    "USERNAME_CREATORE" CHARACTER VARYING(255)
);             
ALTER TABLE "PUBLIC"."CLS_RECENSIONE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_DD" PRIMARY KEY("ID");              
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.CLS_RECENSIONE;          
INSERT INTO "PUBLIC"."CLS_RECENSIONE" VALUES
(2.0, 1, 'Contenuto Recensione', '0', 'Bello, Carino, Avventuroso', 'Turista Aut');             
CREATE MEMORY TABLE "PUBLIC"."CLS_RICHIESTA_AZIONE_DI_CONTRIBUZIONE"(
    "E_AZIONE_DI_CONTRIBUZIONE" TINYINT,
    "DATI_IMMAGINE_ID" BIGINT,
    "DATI_NODO_ID" BIGINT,
    "ID" CHARACTER VARYING(255) NOT NULL,
    "ID_CONTEST" CHARACTER VARYING(255),
    "USERNAME_CREATORE_RICHIESTA" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."CLS_RICHIESTA_AZIONE_DI_CONTRIBUZIONE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3F3" PRIMARY KEY("ID");      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CLS_RICHIESTA_AZIONE_DI_CONTRIBUZIONE;   
CREATE MEMORY TABLE "PUBLIC"."CLS_RICHIESTA_AZIONE_DI_CONTRIBUZIONE_ITINERARIO"(
    "E_AZIONI_DI_CONTRIBUZIONE" TINYINT,
    "DATI_ITINERARIO_ID" BIGINT,
    "ID" CHARACTER VARYING(255) NOT NULL,
    "USERNAME_CREATORE" CHARACTER VARYING(255)
);   
ALTER TABLE "PUBLIC"."CLS_RICHIESTA_AZIONE_DI_CONTRIBUZIONE_ITINERARIO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_809" PRIMARY KEY("ID");           
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CLS_RICHIESTA_AZIONE_DI_CONTRIBUZIONE_ITINERARIO;        
CREATE MEMORY TABLE "PUBLIC"."CLS_SEGNALAZIONE"(
    "ID" BIGINT NOT NULL,
    "DESCRIZIONE" CHARACTER VARYING(255),
    "ID_CONTENUTO" CHARACTER VARYING(255),
    "ID_CURATORE" CHARACTER VARYING(255)
);              
ALTER TABLE "PUBLIC"."CLS_SEGNALAZIONE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_89" PRIMARY KEY("ID");            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CLS_SEGNALAZIONE;        
CREATE MEMORY TABLE "PUBLIC"."CLS_TURISTA_AUTENTICATO"(
    "PUNTEGGIO" INTEGER NOT NULL,
    "RUOLO_UTENTE" TINYINT,
    "ID" BIGINT NOT NULL,
    "DTYPE" CHARACTER VARYING(31) NOT NULL,
    "CREDENZIALI" CHARACTER VARYING(255),
    "ID_COMUNE_ASSOCIATO" CHARACTER VARYING(255)
);              
ALTER TABLE "PUBLIC"."CLS_TURISTA_AUTENTICATO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3A03" PRIMARY KEY("ID");   
-- 6 +/- SELECT COUNT(*) FROM PUBLIC.CLS_TURISTA_AUTENTICATO; 
INSERT INTO "PUBLIC"."CLS_TURISTA_AUTENTICATO" VALUES
(594, 1, 1, 'ClsContributor', 'c c', NULL),
(849, 2, 2, 'ClsContributorAutorizzato', 'ca ca', NULL),
(620, 3, 3, 'ClsAnimatore', 'a a', NULL),
(2147483647, 4, 4, 'ClsCuratore', 'cur cur', NULL),
(2147483647, 5, 5, 'ClsGestoreDellaPiattaforma', 'gdp gdp', NULL),
(0, NULL, 6, 'ClsCuratore', 'null null', NULL);             
ALTER TABLE "PUBLIC"."CLSRDCIMMAGINE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_DC" CHECK("TIPO" IN('INSERISCI_RECENSIONE', 'INSERISCI_IMMAGINE', 'INSERISCI_NODO', 'MODIFICA_NODO', 'ELIMINA_NODO', 'INSERISCI_ITINERARIO', 'MODIFICA_ITINERARIO', 'ELIMINA_ITINERARIO', 'INSERISCI_NODO_CONTEST', 'INSERISCI_FOTO_CONTEST')) NOCHECK;             
ALTER TABLE "PUBLIC"."CLS_RDC_ITINERARIO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" CHECK("STATO" IN('NUOVO', 'ASSEGNATO', 'ACCETTATO', 'RIFUTATO')) NOCHECK;    
ALTER TABLE "PUBLIC"."CLS_NODO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" CHECK("E_TOLOGIA_NODO" BETWEEN 0 AND 2) NOCHECK;       
ALTER TABLE "PUBLIC"."CLSRDCNODO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B28" CHECK("TIPO" IN('INSERISCI_RECENSIONE', 'INSERISCI_IMMAGINE', 'INSERISCI_NODO', 'MODIFICA_NODO', 'ELIMINA_NODO', 'INSERISCI_ITINERARIO', 'MODIFICA_ITINERARIO', 'ELIMINA_ITINERARIO', 'INSERISCI_NODO_CONTEST', 'INSERISCI_FOTO_CONTEST')) NOCHECK;
ALTER TABLE "PUBLIC"."CLS_TURISTA_AUTENTICATO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3A0" CHECK("RUOLO_UTENTE" BETWEEN 0 AND 5) NOCHECK;        
ALTER TABLE "PUBLIC"."CLS_RICHIESTA_AZIONE_DI_CONTRIBUZIONE_ITINERARIO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_80" CHECK("E_AZIONI_DI_CONTRIBUZIONE" BETWEEN 0 AND 9) NOCHECK;   
ALTER TABLE "PUBLIC"."CLSRDCIMMAGINE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" CHECK("STATO" IN('NUOVO', 'ASSEGNATO', 'ACCETTATO', 'RIFUTATO')) NOCHECK;        
ALTER TABLE "PUBLIC"."CLS_RDC_ITINERARIO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5E" CHECK("TIPO" IN('INSERISCI_RECENSIONE', 'INSERISCI_IMMAGINE', 'INSERISCI_NODO', 'MODIFICA_NODO', 'ELIMINA_NODO', 'INSERISCI_ITINERARIO', 'MODIFICA_ITINERARIO', 'ELIMINA_ITINERARIO', 'INSERISCI_NODO_CONTEST', 'INSERISCI_FOTO_CONTEST')) NOCHECK;         
ALTER TABLE "PUBLIC"."CLSRDCNODO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B2" CHECK("STATO" IN('NUOVO', 'ASSEGNATO', 'ACCETTATO', 'RIFUTATO')) NOCHECK;           
ALTER TABLE "PUBLIC"."CLS_RICHIESTA_AZIONE_DI_CONTRIBUZIONE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3F" CHECK("E_AZIONE_DI_CONTRIBUZIONE" BETWEEN 0 AND 9) NOCHECK;              
ALTER TABLE "PUBLIC"."CLS_CONTEST_DI_CONTRIBUZIONE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" UNIQUE("LOCATION_ID");             
ALTER TABLE "PUBLIC"."CLS_COMUNE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" UNIQUE("CURATORI_ASSOCIATI_ID");     
ALTER TABLE "PUBLIC"."CLS_CONTEST_DI_CONTRIBUZIONE" ADD CONSTRAINT "PUBLIC"."FKHD49KWD1PIP1ECADIT9XSL4CV" FOREIGN KEY("LOCATION_ID") REFERENCES "PUBLIC"."CLS_COMUNE"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."CLS_RDC_ITINERARIO" ADD CONSTRAINT "PUBLIC"."FKA0DL2NM3UROOILOJOUD5CD4L" FOREIGN KEY("CREATORE_ID") REFERENCES "PUBLIC"."CLS_TURISTA_AUTENTICATO"("ID") NOCHECK;        
ALTER TABLE "PUBLIC"."CLSRDCIMMAGINE" ADD CONSTRAINT "PUBLIC"."FKBJ6TUISUA9R5XYX25P9F26VQ7" FOREIGN KEY("RESPONSABILE_ID") REFERENCES "PUBLIC"."CLS_TURISTA_AUTENTICATO"("ID") NOCHECK;       
ALTER TABLE "PUBLIC"."CLSRDCNODO" ADD CONSTRAINT "PUBLIC"."FKOQHGHXFO8PRI8GNLHN6T8TV79" FOREIGN KEY("CREATORE_ID") REFERENCES "PUBLIC"."CLS_TURISTA_AUTENTICATO"("ID") NOCHECK;               
ALTER TABLE "PUBLIC"."CLS_RDC_ITINERARIO" ADD CONSTRAINT "PUBLIC"."FK708LWT4R1B89TPKM9SWW211XO" FOREIGN KEY("RESPONSABILE_ID") REFERENCES "PUBLIC"."CLS_TURISTA_AUTENTICATO"("ID") NOCHECK;   
ALTER TABLE "PUBLIC"."CLS_RICHIESTA_AZIONE_DI_CONTRIBUZIONE" ADD CONSTRAINT "PUBLIC"."FK4YBBTW7UI43DO8D2IHYBG0V7E" FOREIGN KEY("DATI_NODO_ID") REFERENCES "PUBLIC"."CLS_NODO"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."CLS_RDC_ITINERARIO" ADD CONSTRAINT "PUBLIC"."FKB14BSC2KU2SIFPOVGPBSPOG3B" FOREIGN KEY("OLD_DATA_ID") REFERENCES "PUBLIC"."CLS_ITINERARIO"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."CLS_RDC_ITINERARIO" ADD CONSTRAINT "PUBLIC"."FKP3RU12EGE4TD4P585JTSMPVB2" FOREIGN KEY("NEW_DATA_ID") REFERENCES "PUBLIC"."CLS_ITINERARIO"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."CLS_ITINERARIO_TAPPE" ADD CONSTRAINT "PUBLIC"."FKG2FDNF5QP8UEUCO1IAWJWFFYM" FOREIGN KEY("TAPPE_ID") REFERENCES "PUBLIC"."CLS_NODO"("ID") NOCHECK;       
ALTER TABLE "PUBLIC"."CLS_COMUNE" ADD CONSTRAINT "PUBLIC"."FK4MEF7K7XPTAGOU0YHY1YG5F84" FOREIGN KEY("CURATORI_ASSOCIATI_ID") REFERENCES "PUBLIC"."CLS_TURISTA_AUTENTICATO"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."CLSRDCNODO" ADD CONSTRAINT "PUBLIC"."FK319E8X22D2QL7SIAEPG3QGL28" FOREIGN KEY("NEW_DATA_ID") REFERENCES "PUBLIC"."CLS_NODO"("ID") NOCHECK;              
ALTER TABLE "PUBLIC"."CLSRDCNODO" ADD CONSTRAINT "PUBLIC"."FKF7SGOVAWKMY7BU2R5B053WLI4" FOREIGN KEY("RESPONSABILE_ID") REFERENCES "PUBLIC"."CLS_TURISTA_AUTENTICATO"("ID") NOCHECK;           
ALTER TABLE "PUBLIC"."CLSRDCNODO" ADD CONSTRAINT "PUBLIC"."FKT7TEC538TNAH6C2H52W0NTE68" FOREIGN KEY("ID_CONTEST_ID") REFERENCES "PUBLIC"."CLS_CONTEST_DI_CONTRIBUZIONE"("ID") NOCHECK;        
ALTER TABLE "PUBLIC"."CLSRDCNODO" ADD CONSTRAINT "PUBLIC"."FKFOR10HEQ7O2E9P364UIT2LL1Q" FOREIGN KEY("OLD_DATA_ID") REFERENCES "PUBLIC"."CLS_NODO"("ID") NOCHECK;              
ALTER TABLE "PUBLIC"."CLS_ITINERARIO_TAPPE" ADD CONSTRAINT "PUBLIC"."FK5VYEBMLJ0GC1JPBFBI5DBW20F" FOREIGN KEY("CLS_ITINERARIO_ID") REFERENCES "PUBLIC"."CLS_ITINERARIO"("ID") NOCHECK;        
ALTER TABLE "PUBLIC"."CLSRDCIMMAGINE" ADD CONSTRAINT "PUBLIC"."FK9DU4CW9EA27HHBUOECB2D3IB4" FOREIGN KEY("ID_CONTEST_ID") REFERENCES "PUBLIC"."CLS_CONTEST_DI_CONTRIBUZIONE"("ID") NOCHECK;    
ALTER TABLE "PUBLIC"."CLSRDCIMMAGINE" ADD CONSTRAINT "PUBLIC"."FK58RMJH8KXTCE7JOBKGDEX1EM0" FOREIGN KEY("OLD_DATA_ID") REFERENCES "PUBLIC"."CLS_IMMAGINE"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."CLS_RICHIESTA_AZIONE_DI_CONTRIBUZIONE_ITINERARIO" ADD CONSTRAINT "PUBLIC"."FK8H24CJ8A2V6YT741B22ENMXSG" FOREIGN KEY("DATI_ITINERARIO_ID") REFERENCES "PUBLIC"."CLS_ITINERARIO"("ID") NOCHECK;           
ALTER TABLE "PUBLIC"."CLS_RDC_ITINERARIO" ADD CONSTRAINT "PUBLIC"."FKMLW1HFP4GE6660HCR3MIACUJA" FOREIGN KEY("ID_CONTEST_ID") REFERENCES "PUBLIC"."CLS_CONTEST_DI_CONTRIBUZIONE"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."CLSRDCIMMAGINE" ADD CONSTRAINT "PUBLIC"."FKC9997EFHBOIR6CTNH6QW29QVR" FOREIGN KEY("NEW_DATA_ID") REFERENCES "PUBLIC"."CLS_IMMAGINE"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."CLS_RICHIESTA_AZIONE_DI_CONTRIBUZIONE" ADD CONSTRAINT "PUBLIC"."FKFFY07YN7H6M3N9OMLDYYJTWH2" FOREIGN KEY("DATI_IMMAGINE_ID") REFERENCES "PUBLIC"."CLS_IMMAGINE"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."CLSRDCIMMAGINE" ADD CONSTRAINT "PUBLIC"."FKEW3UFQNNFL267PDBNJRERYKP0" FOREIGN KEY("CREATORE_ID") REFERENCES "PUBLIC"."CLS_TURISTA_AUTENTICATO"("ID") NOCHECK;           
